"""Acceptance Criteria extraction utilities for Jira descriptions.

This module provides functions to extract existing acceptance criteria from
Jira ticket descriptions and replace the AC section in ADF documents.
"""

from __future__ import annotations

import logging
import re

from src.jira.ac_formatter import format_acs_to_adf

logger = logging.getLogger(__name__)

# Pattern to match the AC section header
AC_HEADER_PATTERN = re.compile(
    r"^##\s*Acceptance\s+Criteria\s*$", re.MULTILINE | re.IGNORECASE
)

# Pattern to match checkbox items (checked or unchecked)
AC_ITEM_PATTERN = re.compile(r"^\s*-\s*\[([ xX])\]\s*(.+)$", re.MULTILINE)

# Pattern to match the attribution footer
ATTRIBUTION_PATTERN = re.compile(
    r"^---\s*\n\*Generated by Jira AC Assistant.*?\*\s*$",
    re.MULTILINE | re.DOTALL,
)


def extract_acs_from_description(description: str) -> list[str]:
    """Extract acceptance criteria from a plain text description.

    Searches for the "## Acceptance Criteria" section and parses each
    criterion line (starting with `- [ ]` or `- [x]`).

    Args:
        description: The plain text description to parse.

    Returns:
        List of criterion strings (without the checkbox prefix).
        Returns empty list if no AC section found or if the description is empty.
    """
    if not description or not isinstance(description, str):
        return []

    # Find the AC section header
    header_match = AC_HEADER_PATTERN.search(description)
    if not header_match:
        logger.debug("No Acceptance Criteria section found in description")
        return []

    # Get the text after the header
    section_start = header_match.end()
    ac_section = description[section_start:]

    # Remove attribution footer if present (to avoid including it in parsing)
    ac_section = ATTRIBUTION_PATTERN.sub("", ac_section)

    # Find the next section header (##) to limit our search
    next_section_match = re.search(r"^##\s+", ac_section, re.MULTILINE)
    if next_section_match:
        ac_section = ac_section[: next_section_match.start()]

    # Extract all checkbox items
    criteria: list[str] = []
    for match in AC_ITEM_PATTERN.finditer(ac_section):
        criterion_text = match.group(2).strip()
        if criterion_text:
            criteria.append(criterion_text)

    return criteria


def extract_acs_from_adf(description_adf: dict | None) -> list[str]:
    """Extract acceptance criteria directly from an ADF document structure.

    Locates the AC section by heading, then extracts text from taskList
    and bulletList items. Handles both tool-generated ACs (taskList format)
    and manually-written ACs (bulletList format).

    Args:
        description_adf: The description in Atlassian Document Format, or None.

    Returns:
        List of criterion strings extracted from list items in the AC section.
        Returns empty list if no AC section found or input is None.
    """
    if not description_adf or not isinstance(description_adf, dict):
        return []

    content = description_adf.get("content", [])
    if not isinstance(content, list) or not content:
        return []

    start_idx, end_idx = _find_ac_section_indices(content)
    if start_idx is None or end_idx is None:
        logger.debug("No Acceptance Criteria section found in ADF")
        return []

    criteria: list[str] = []

    for node in content[start_idx + 1 : end_idx]:
        node_type = node.get("type", "")

        if node_type in ("taskList", "bulletList", "orderedList"):
            for item in node.get("content", []):
                item_text = _extract_text_from_node(item).strip()
                # Remove leading checkbox markers from manual Jira ACs
                if item_text.startswith(("[ ] ", "[x] ", "[X] ")):
                    item_text = item_text[4:]
                if item_text:
                    criteria.append(item_text)

    return criteria


def _find_ac_section_indices(content: list[dict]) -> tuple[int | None, int | None]:
    """Find the start and end indices of the AC section in ADF content.

    The AC section starts with a heading containing "Acceptance Criteria"
    and extends until:
    - The attribution paragraph (containing "Jira AC Assistant")
    - Another heading of the same or higher level
    - The end of the document

    Args:
        content: The content list from an ADF document.

    Returns:
        Tuple of (start_index, end_index) where end_index is exclusive.
        Returns (None, None) if no AC section is found.
    """
    start_idx: int | None = None
    end_idx: int | None = None
    ac_heading_level: int | None = None

    for i, node in enumerate(content):
        node_type = node.get("type", "")

        # Look for the AC heading
        if start_idx is None:
            if node_type == "heading":
                heading_text = _extract_text_from_node(node)
                if "acceptance criteria" in heading_text.lower():
                    start_idx = i
                    ac_heading_level = node.get("attrs", {}).get("level", 2)
            continue

        # We're in the AC section, look for the end
        # Check for attribution paragraph
        if node_type == "paragraph":
            para_text = _extract_text_from_node(node)
            if "jira ac assistant" in para_text.lower():
                end_idx = i + 1  # Include the attribution
                break

        # Check for another heading at same or higher level
        if node_type == "heading":
            heading_level = node.get("attrs", {}).get("level", 2)
            if heading_level <= ac_heading_level:
                end_idx = i
                break

    # If we found a start but no end, the AC section goes to the end
    if start_idx is not None and end_idx is None:
        end_idx = len(content)

    return start_idx, end_idx


def _extract_text_from_node(node: dict) -> str:
    """Extract plain text from an ADF node recursively.

    Args:
        node: An ADF node dictionary.

    Returns:
        Concatenated text content from the node and its children.
    """
    if not isinstance(node, dict):
        return ""

    texts: list[str] = []

    # Direct text content
    if "text" in node:
        texts.append(str(node["text"]))

    # Recursive content
    content = node.get("content", [])
    if isinstance(content, list):
        for child in content:
            texts.append(_extract_text_from_node(child))

    return " ".join(texts)


def replace_acs_in_adf(existing_adf: dict | None, new_acs: list[str]) -> dict:
    """Replace the AC section in an ADF document with new acceptance criteria.

    If the existing document has an AC section, it will be replaced.
    If no AC section exists, the new ACs will be appended.
    If existing_adf is None, a new document with just the AC section is created.

    Args:
        existing_adf: The existing description in ADF format, or None.
        new_acs: List of new acceptance criteria strings.

    Returns:
        Updated ADF document with the new AC section.
        If new_acs is empty/invalid and no existing content, returns an empty document.
    """
    # Generate the new AC section ADF
    new_acs_adf = format_acs_to_adf(new_acs)

    # Handle None or invalid existing_adf
    if existing_adf is None or not isinstance(existing_adf, dict):
        if new_acs_adf is None:
            # Return empty document if no valid ACs
            return {"type": "doc", "version": 1, "content": []}
        return new_acs_adf

    # Get existing content
    existing_content = existing_adf.get("content", [])
    if not isinstance(existing_content, list):
        existing_content = []

    # If no existing content, just return the new ACs
    if not existing_content:
        if new_acs_adf is None:
            return {"type": "doc", "version": 1, "content": []}
        return new_acs_adf

    # Find the AC section in existing content
    start_idx, end_idx = _find_ac_section_indices(existing_content)

    # Get the new AC content nodes (from the generated ADF)
    new_ac_nodes = new_acs_adf.get("content", []) if new_acs_adf else []

    if start_idx is not None and end_idx is not None:
        # Replace the existing AC section
        new_content = (
            list(existing_content[:start_idx])
            + list(new_ac_nodes)
            + list(existing_content[end_idx:])
        )
    else:
        # No existing AC section, append the new ACs
        new_content = list(existing_content) + list(new_ac_nodes)

    return {
        "type": "doc",
        "version": 1,
        "content": new_content,
    }
