"""Acceptance Criteria formatter for Jira Atlassian Document Format (ADF)."""

import logging
import uuid
from datetime import datetime, timezone

logger = logging.getLogger(__name__)


def validate_acs(acs: list[str], ticket_key: str | None = None) -> bool:
    """Validate that the acceptance criteria list is non-empty and valid.

    Args:
        acs: List of acceptance criteria strings.
        ticket_key: Optional ticket key for logging context.

    Returns:
        True if the list contains at least one valid AC, False otherwise.
    """
    if not acs:
        context = f" for {ticket_key}" if ticket_key else ""
        logger.warning("Empty acceptance criteria list%s", context)
        return False

    # Filter out non-string or empty items
    valid_acs = [ac for ac in acs if isinstance(ac, str) and ac.strip()]
    if not valid_acs:
        context = f" for {ticket_key}" if ticket_key else ""
        logger.warning("No valid acceptance criteria after filtering%s", context)
        return False

    return True


def _generate_local_id() -> str:
    """Generate a unique local ID for ADF nodes.

    Returns:
        A UUID string for use as ADF localId attribute.
    """
    return str(uuid.uuid4())


def build_attribution_node() -> dict:
    """Build an ADF paragraph node with attribution and timestamp.

    Returns:
        ADF paragraph node with italicized attribution text.
    """
    now = datetime.now(timezone.utc)
    # Human-friendly format: "January 15, 2024 at 2:30 PM UTC"
    timestamp = now.strftime("%B %d, %Y at %-I:%M %p UTC")

    return {
        "type": "paragraph",
        "content": [
            {
                "type": "text",
                "text": f"Generated by Jira AC Assistant on {timestamp}",
                "marks": [{"type": "em"}],
            }
        ],
    }


def format_acs_to_adf(acs: list[str]) -> dict | None:
    """Convert a list of acceptance criteria to ADF format.

    Creates an ADF structure with:
    - Heading level 2: "Acceptance Criteria"
    - TaskList with checkbox items for each AC
    - Attribution paragraph with timestamp

    Args:
        acs: List of acceptance criteria strings.

    Returns:
        ADF document dict, or None if the list is empty/invalid.
    """
    # Filter to valid strings only
    valid_acs = [ac.strip() for ac in acs if isinstance(ac, str) and ac.strip()]

    if not valid_acs:
        return None

    # Build task items for each AC
    task_items = []
    for ac in valid_acs:
        task_items.append({
            "type": "taskItem",
            "attrs": {
                "localId": _generate_local_id(),
                "state": "TODO",
            },
            "content": [{"type": "text", "text": ac}],
        })

    # Build the complete ADF structure
    content = [
        # Heading
        {
            "type": "heading",
            "attrs": {"level": 2},
            "content": [{"type": "text", "text": "Acceptance Criteria"}],
        },
        # Task list with checkboxes
        {
            "type": "taskList",
            "attrs": {"localId": _generate_local_id()},
            "content": task_items,
        },
        # Attribution
        build_attribution_node(),
    ]

    return {
        "type": "doc",
        "version": 1,
        "content": content,
    }


def append_acs_to_description(
    existing_adf: dict | None,
    new_acs: list[str],
) -> dict | None:
    """Append new acceptance criteria to an existing description.

    If the description already has content, the new ACs are appended
    after the existing content. If the description is empty/None,
    returns just the new ACs formatted as ADF.

    Args:
        existing_adf: The existing description in ADF format, or None.
        new_acs: List of new acceptance criteria to append.

    Returns:
        Updated ADF document with new ACs appended, or None if no valid ACs.
    """
    new_acs_adf = format_acs_to_adf(new_acs)

    if new_acs_adf is None:
        return existing_adf

    # If no existing description, return just the new ACs
    if existing_adf is None or not isinstance(existing_adf, dict):
        return new_acs_adf

    # Get existing content
    existing_content = existing_adf.get("content", [])
    if not isinstance(existing_content, list):
        existing_content = []

    # Get new AC content (skip the outer doc wrapper)
    new_content = new_acs_adf.get("content", [])

    # Merge: existing content + new AC content
    merged_content = list(existing_content) + list(new_content)

    return {
        "type": "doc",
        "version": 1,
        "content": merged_content,
    }
