"""Integration tests for writing ACs back to Jira.

These tests verify the AC write functionality against a real Jira instance.
They require real Jira credentials to run:
- JIRA_BASE_URL: Jira Cloud instance URL (e.g., https://company.atlassian.net)
- JIRA_USER_EMAIL: API user email
- JIRA_API_TOKEN: API token (from Atlassian account)

Tests are skipped automatically if JIRA_API_TOKEN is not set.
"""

from __future__ import annotations

from datetime import datetime, timezone

import pytest

from src.jira import JiraClient
from src.jira.ac_formatter import (
    append_acs_to_description,
    format_acs_to_adf,
    validate_acs,
)


# Test ticket key in the IGAL project
TEST_TICKET_KEY = "IGAL-1928"


@pytest.mark.integration
class TestJiraWriteIntegration:
    """Integration tests for Jira AC write functionality."""

    @pytest.mark.asyncio
    async def test_write_acs_to_real_ticket(
        self, requires_jira_credentials, jira_client: JiraClient
    ) -> None:
        """Test writing ACs to a real Jira ticket.

        This test:
        1. Generates test acceptance criteria
        2. Formats them using format_acs_to_adf()
        3. Writes to the ticket using jira_client.update_description()
        4. Fetches the ticket again using jira_client.get_ticket()
        5. Verifies the description contains the ACs
        """
        # Generate unique test ACs with timestamp to verify we're seeing fresh data
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        test_acs = [
            f"[Test {timestamp}] User can log in with valid credentials",
            f"[Test {timestamp}] System displays error message for invalid login",
            f"[Test {timestamp}] User session expires after 30 minutes of inactivity",
        ]

        # Validate ACs before formatting
        assert validate_acs(test_acs, TEST_TICKET_KEY), "Test ACs should be valid"

        # Format ACs to ADF
        acs_adf = format_acs_to_adf(test_acs)
        assert acs_adf is not None, "ADF should not be None for valid ACs"
        assert acs_adf.get("type") == "doc", "ADF should have 'doc' type"
        assert acs_adf.get("version") == 1, "ADF should have version 1"

        # Write to Jira ticket
        update_result = await jira_client.update_description(TEST_TICKET_KEY, acs_adf)
        assert update_result is True, f"Failed to update description for {TEST_TICKET_KEY}"

        # Fetch the ticket again to verify
        updated_ticket = await jira_client.get_ticket(TEST_TICKET_KEY)
        assert updated_ticket.key == TEST_TICKET_KEY, "Ticket key should match"

        # Verify the description contains our test ACs
        # The description is extracted as plain text from ADF
        description = updated_ticket.description
        assert description is not None, "Description should not be None"

        # Check that all our test ACs appear in the description
        for ac in test_acs:
            assert ac in description, f"AC '{ac}' should be in the description"

        # Verify the heading is present
        assert "Acceptance Criteria" in description, "AC heading should be in description"

        # Verify attribution is present
        assert "Generated by Jira AC Assistant" in description, (
            "Attribution should be in description"
        )

    @pytest.mark.asyncio
    async def test_append_acs_to_existing(
        self, requires_jira_credentials, jira_client: JiraClient
    ) -> None:
        """Test appending ACs to a ticket that already has ACs.

        This test:
        1. First writes an initial set of ACs to the ticket
        2. Then appends another set using append_acs_to_description()
        3. Fetches the ticket
        4. Verifies BOTH sets of ACs are present in the description
        """
        # First, write initial ACs to establish baseline
        timestamp = datetime.now(timezone.utc).strftime("%Y-%m-%d %H:%M:%S UTC")
        initial_acs = [
            f"[Initial {timestamp}] System validates email format",
            f"[Initial {timestamp}] Password must be at least 8 characters",
        ]

        # Format and write initial ACs
        initial_adf = format_acs_to_adf(initial_acs)
        assert initial_adf is not None, "Initial ADF should not be None"

        initial_update = await jira_client.update_description(TEST_TICKET_KEY, initial_adf)
        assert initial_update is True, "Initial update should succeed"

        # Fetch ticket to get current ADF
        ticket_after_initial = await jira_client.get_ticket(TEST_TICKET_KEY)
        existing_adf = ticket_after_initial.description_adf

        # Verify initial ACs are present
        for ac in initial_acs:
            assert ac in ticket_after_initial.description, (
                f"Initial AC '{ac}' should be in description"
            )

        # Create additional ACs to append
        additional_acs = [
            f"[Appended {timestamp}] User receives confirmation email",
            f"[Appended {timestamp}] Account is locked after 5 failed attempts",
        ]

        # Use append_acs_to_description to merge
        merged_adf = append_acs_to_description(existing_adf, additional_acs)
        assert merged_adf is not None, "Merged ADF should not be None"
        assert merged_adf.get("type") == "doc", "Merged ADF should have 'doc' type"

        # Write merged ADF back to Jira
        append_update = await jira_client.update_description(TEST_TICKET_KEY, merged_adf)
        assert append_update is True, "Append update should succeed"

        # Fetch ticket again to verify both sets
        final_ticket = await jira_client.get_ticket(TEST_TICKET_KEY)
        final_description = final_ticket.description

        # Verify ALL ACs (both initial and appended) are present
        all_acs = initial_acs + additional_acs
        for ac in all_acs:
            assert ac in final_description, (
                f"AC '{ac}' should be in final description after append"
            )

        # Verify the AC heading appears (at least once, possibly twice)
        assert "Acceptance Criteria" in final_description, (
            "AC heading should be in final description"
        )

        # Verify attribution is present
        assert "Generated by Jira AC Assistant" in final_description, (
            "Attribution should be in final description"
        )
