"""Unit tests for AC extractor module."""

from src.jira.ac_extractor import (
    extract_acs_from_adf,
    extract_acs_from_description,
    replace_acs_in_adf,
)


class TestExtractAcsFromDescription:
    """Test suite for extract_acs_from_description function."""

    def test_extract_multiple_criteria(self):
        """Test extracting multiple acceptance criteria from a description."""
        description = """Some introduction text.

## Acceptance Criteria

- [ ] User can log in with valid credentials
- [ ] User sees error message with invalid credentials
- [ ] User is redirected to dashboard after login

Some footer text.
"""
        result = extract_acs_from_description(description)

        assert len(result) == 3
        assert result[0] == "User can log in with valid credentials"
        assert result[1] == "User sees error message with invalid credentials"
        assert result[2] == "User is redirected to dashboard after login"

    def test_extract_checked_and_unchecked_criteria(self):
        """Test extracting both checked and unchecked criteria."""
        description = """## Acceptance Criteria

- [x] First criterion (completed)
- [ ] Second criterion (pending)
- [X] Third criterion (completed with uppercase X)
"""
        result = extract_acs_from_description(description)

        assert len(result) == 3
        assert result[0] == "First criterion (completed)"
        assert result[1] == "Second criterion (pending)"
        assert result[2] == "Third criterion (completed with uppercase X)"

    def test_extract_returns_empty_list_when_no_ac_section(self):
        """Test that empty list is returned when no AC section exists."""
        description = """This is a regular description.

No acceptance criteria here.

Just some text.
"""
        result = extract_acs_from_description(description)

        assert result == []

    def test_extract_returns_empty_list_when_ac_section_has_no_criteria(self):
        """Test that empty list is returned when AC section has no criteria."""
        description = """## Acceptance Criteria

This section has no checkbox items.
Just regular text.
"""
        result = extract_acs_from_description(description)

        assert result == []

    def test_extract_handles_attribution_footer(self):
        """Test extraction with attribution footer present."""
        description = """## Acceptance Criteria

- [ ] First criterion
- [ ] Second criterion

---
*Generated by Jira AC Assistant on January 15, 2024 at 2:30 PM UTC*
"""
        result = extract_acs_from_description(description)

        assert len(result) == 2
        assert result[0] == "First criterion"
        assert result[1] == "Second criterion"

    def test_extract_empty_description(self):
        """Test extraction with empty description."""
        result = extract_acs_from_description("")

        assert result == []

    def test_extract_none_description(self):
        """Test extraction with None description."""
        result = extract_acs_from_description(None)

        assert result == []

    def test_extract_description_with_only_header(self):
        """Test extraction when description has only the header."""
        description = "## Acceptance Criteria"

        result = extract_acs_from_description(description)

        assert result == []

    def test_extract_case_insensitive_header(self):
        """Test that header matching is case-insensitive."""
        description = """## acceptance criteria

- [ ] First criterion
"""
        result = extract_acs_from_description(description)

        assert len(result) == 1
        assert result[0] == "First criterion"

    def test_extract_with_extra_whitespace(self):
        """Test extraction handles extra whitespace in items."""
        description = """## Acceptance Criteria

- [ ]   Extra spaces before text
- [ ] Normal text
"""
        result = extract_acs_from_description(description)

        assert len(result) == 2
        assert result[0] == "Extra spaces before text"
        assert result[1] == "Normal text"

    def test_extract_stops_at_next_section(self):
        """Test that extraction stops at the next section header."""
        description = """## Acceptance Criteria

- [ ] First criterion

## Implementation Notes

- [ ] This should not be extracted
"""
        result = extract_acs_from_description(description)

        assert len(result) == 1
        assert result[0] == "First criterion"

    def test_extract_with_content_before_ac_section(self):
        """Test extraction with content before AC section."""
        description = """# Story Title

As a user, I want to login.

## Background

Some background info.

## Acceptance Criteria

- [ ] Criterion after other sections
"""
        result = extract_acs_from_description(description)

        assert len(result) == 1
        assert result[0] == "Criterion after other sections"

    def test_extract_multiline_criteria_gets_first_line(self):
        """Test that only the first line of a criterion is captured."""
        description = """## Acceptance Criteria

- [ ] First line of criterion
  Continuation that should not be included
- [ ] Second criterion
"""
        result = extract_acs_from_description(description)

        assert len(result) == 2
        assert result[0] == "First line of criterion"
        assert result[1] == "Second criterion"


class TestExtractAcsFromAdf:
    """Test suite for extract_acs_from_adf function."""

    def test_extract_from_tool_generated_task_list(self):
        """Test extracting ACs from tool-generated taskList format."""
        adf = {
            "type": "doc",
            "version": 1,
            "content": [
                {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": "Description text"}],
                },
                {
                    "type": "heading",
                    "attrs": {"level": 2},
                    "content": [{"type": "text", "text": "Acceptance Criteria"}],
                },
                {
                    "type": "taskList",
                    "attrs": {"localId": "tl-1"},
                    "content": [
                        {
                            "type": "taskItem",
                            "attrs": {"localId": "ti-1", "state": "TODO"},
                            "content": [
                                {"type": "text", "text": "Given a user logs in, "},
                                {
                                    "type": "text",
                                    "text": "they see the dashboard",
                                    "marks": [{"type": "strong"}],
                                },
                            ],
                        },
                        {
                            "type": "taskItem",
                            "attrs": {"localId": "ti-2", "state": "TODO"},
                            "content": [
                                {"type": "text", "text": "User can log out"}
                            ],
                        },
                    ],
                },
                {
                    "type": "paragraph",
                    "content": [
                        {
                            "type": "text",
                            "text": "Generated by Jira AC Assistant on Jan 1",
                            "marks": [{"type": "em"}],
                        }
                    ],
                },
            ],
        }

        result = extract_acs_from_adf(adf)

        assert len(result) == 2
        assert "Given a user logs in" in result[0]
        assert "they see the dashboard" in result[0]
        assert result[1] == "User can log out"

    def test_extract_from_manually_written_bullet_list(self):
        """Test extracting ACs from manually-written bulletList format."""
        adf = {
            "type": "doc",
            "version": 1,
            "content": [
                {
                    "type": "heading",
                    "attrs": {"level": 2},
                    "content": [{"type": "text", "text": "Acceptance Criteria"}],
                },
                {
                    "type": "bulletList",
                    "content": [
                        {
                            "type": "listItem",
                            "content": [
                                {
                                    "type": "paragraph",
                                    "content": [
                                        {"type": "text", "text": "First criterion"}
                                    ],
                                }
                            ],
                        },
                        {
                            "type": "listItem",
                            "content": [
                                {
                                    "type": "paragraph",
                                    "content": [
                                        {"type": "text", "text": "Second criterion"}
                                    ],
                                }
                            ],
                        },
                    ],
                },
            ],
        }

        result = extract_acs_from_adf(adf)

        assert len(result) == 2
        assert result[0] == "First criterion"
        assert result[1] == "Second criterion"

    def test_extract_from_ordered_list(self):
        """Test extracting ACs from orderedList format."""
        adf = {
            "type": "doc",
            "version": 1,
            "content": [
                {
                    "type": "heading",
                    "attrs": {"level": 2},
                    "content": [{"type": "text", "text": "Acceptance Criteria"}],
                },
                {
                    "type": "orderedList",
                    "content": [
                        {
                            "type": "listItem",
                            "content": [
                                {
                                    "type": "paragraph",
                                    "content": [
                                        {"type": "text", "text": "First criterion"}
                                    ],
                                }
                            ],
                        },
                    ],
                },
            ],
        }

        result = extract_acs_from_adf(adf)

        assert len(result) == 1
        assert result[0] == "First criterion"

    def test_extract_strips_checkbox_markers(self):
        """Test that leading checkbox markers are stripped from items."""
        adf = {
            "type": "doc",
            "version": 1,
            "content": [
                {
                    "type": "heading",
                    "attrs": {"level": 2},
                    "content": [{"type": "text", "text": "Acceptance Criteria"}],
                },
                {
                    "type": "bulletList",
                    "content": [
                        {
                            "type": "listItem",
                            "content": [
                                {
                                    "type": "paragraph",
                                    "content": [
                                        {
                                            "type": "text",
                                            "text": "[ ] Unchecked item",
                                        }
                                    ],
                                }
                            ],
                        },
                        {
                            "type": "listItem",
                            "content": [
                                {
                                    "type": "paragraph",
                                    "content": [
                                        {
                                            "type": "text",
                                            "text": "[x] Checked item",
                                        }
                                    ],
                                }
                            ],
                        },
                        {
                            "type": "listItem",
                            "content": [
                                {
                                    "type": "paragraph",
                                    "content": [
                                        {
                                            "type": "text",
                                            "text": "[X] Uppercase checked item",
                                        }
                                    ],
                                }
                            ],
                        },
                    ],
                },
            ],
        }

        result = extract_acs_from_adf(adf)

        assert len(result) == 3
        assert result[0] == "Unchecked item"
        assert result[1] == "Checked item"
        assert result[2] == "Uppercase checked item"

    def test_extract_returns_empty_for_none_input(self):
        """Test that None input returns empty list."""
        assert extract_acs_from_adf(None) == []

    def test_extract_returns_empty_for_non_dict_input(self):
        """Test that non-dict input returns empty list."""
        assert extract_acs_from_adf("not a dict") == []
        assert extract_acs_from_adf(42) == []
        assert extract_acs_from_adf([]) == []

    def test_extract_returns_empty_for_empty_adf(self):
        """Test that empty ADF returns empty list."""
        assert extract_acs_from_adf({}) == []
        assert extract_acs_from_adf({"type": "doc", "version": 1}) == []
        assert extract_acs_from_adf({"type": "doc", "content": []}) == []

    def test_extract_returns_empty_when_no_ac_section(self):
        """Test that ADF without AC heading returns empty list."""
        adf = {
            "type": "doc",
            "version": 1,
            "content": [
                {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": "Just a description"}],
                },
                {
                    "type": "heading",
                    "attrs": {"level": 2},
                    "content": [{"type": "text", "text": "Technical Notes"}],
                },
            ],
        }

        assert extract_acs_from_adf(adf) == []

    def test_extract_stops_at_next_heading(self):
        """Test that extraction stops at the next heading of same or higher level."""
        adf = {
            "type": "doc",
            "version": 1,
            "content": [
                {
                    "type": "heading",
                    "attrs": {"level": 2},
                    "content": [{"type": "text", "text": "Acceptance Criteria"}],
                },
                {
                    "type": "taskList",
                    "attrs": {"localId": "tl-1"},
                    "content": [
                        {
                            "type": "taskItem",
                            "attrs": {"localId": "ti-1", "state": "TODO"},
                            "content": [
                                {"type": "text", "text": "Should be extracted"}
                            ],
                        },
                    ],
                },
                {
                    "type": "heading",
                    "attrs": {"level": 2},
                    "content": [{"type": "text", "text": "Other Section"}],
                },
                {
                    "type": "bulletList",
                    "content": [
                        {
                            "type": "listItem",
                            "content": [
                                {
                                    "type": "paragraph",
                                    "content": [
                                        {
                                            "type": "text",
                                            "text": "Should NOT be extracted",
                                        }
                                    ],
                                }
                            ],
                        },
                    ],
                },
            ],
        }

        result = extract_acs_from_adf(adf)

        assert len(result) == 1
        assert result[0] == "Should be extracted"

    def test_extract_case_insensitive_heading(self):
        """Test that AC heading match is case-insensitive."""
        adf = {
            "type": "doc",
            "version": 1,
            "content": [
                {
                    "type": "heading",
                    "attrs": {"level": 2},
                    "content": [{"type": "text", "text": "acceptance criteria"}],
                },
                {
                    "type": "taskList",
                    "attrs": {"localId": "tl-1"},
                    "content": [
                        {
                            "type": "taskItem",
                            "attrs": {"localId": "ti-1", "state": "TODO"},
                            "content": [{"type": "text", "text": "Found it"}],
                        },
                    ],
                },
            ],
        }

        result = extract_acs_from_adf(adf)

        assert len(result) == 1
        assert result[0] == "Found it"

    def test_extract_skips_empty_items(self):
        """Test that empty list items are skipped."""
        adf = {
            "type": "doc",
            "version": 1,
            "content": [
                {
                    "type": "heading",
                    "attrs": {"level": 2},
                    "content": [{"type": "text", "text": "Acceptance Criteria"}],
                },
                {
                    "type": "taskList",
                    "attrs": {"localId": "tl-1"},
                    "content": [
                        {
                            "type": "taskItem",
                            "attrs": {"localId": "ti-1", "state": "TODO"},
                            "content": [{"type": "text", "text": "Valid item"}],
                        },
                        {
                            "type": "taskItem",
                            "attrs": {"localId": "ti-2", "state": "TODO"},
                            "content": [],
                        },
                        {
                            "type": "taskItem",
                            "attrs": {"localId": "ti-3", "state": "TODO"},
                            "content": [{"type": "text", "text": "   "}],
                        },
                    ],
                },
            ],
        }

        result = extract_acs_from_adf(adf)

        assert len(result) == 1
        assert result[0] == "Valid item"

    def test_extract_with_nested_formatting(self):
        """Test extracting ACs that have nested formatting marks."""
        adf = {
            "type": "doc",
            "version": 1,
            "content": [
                {
                    "type": "heading",
                    "attrs": {"level": 2},
                    "content": [{"type": "text", "text": "Acceptance Criteria"}],
                },
                {
                    "type": "taskList",
                    "attrs": {"localId": "tl-1"},
                    "content": [
                        {
                            "type": "taskItem",
                            "attrs": {"localId": "ti-1", "state": "TODO"},
                            "content": [
                                {"type": "text", "text": "Given "},
                                {
                                    "type": "text",
                                    "text": "a valid user",
                                    "marks": [{"type": "strong"}],
                                },
                                {"type": "text", "text": " logs in"},
                            ],
                        },
                    ],
                },
            ],
        }

        result = extract_acs_from_adf(adf)

        assert len(result) == 1
        # _extract_text_from_node joins sibling texts with spaces
        assert "Given" in result[0]
        assert "a valid user" in result[0]
        assert "logs in" in result[0]

    def test_extract_ignores_non_list_content_in_ac_section(self):
        """Test that non-list nodes in the AC section are ignored."""
        adf = {
            "type": "doc",
            "version": 1,
            "content": [
                {
                    "type": "heading",
                    "attrs": {"level": 2},
                    "content": [{"type": "text", "text": "Acceptance Criteria"}],
                },
                {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": "Some intro text"}],
                },
                {
                    "type": "taskList",
                    "attrs": {"localId": "tl-1"},
                    "content": [
                        {
                            "type": "taskItem",
                            "attrs": {"localId": "ti-1", "state": "TODO"},
                            "content": [
                                {"type": "text", "text": "Actual criterion"}
                            ],
                        },
                    ],
                },
            ],
        }

        result = extract_acs_from_adf(adf)

        assert len(result) == 1
        assert result[0] == "Actual criterion"


class TestReplaceAcsInAdf:
    """Test suite for replace_acs_in_adf function."""

    def test_replace_in_existing_adf_with_ac_section(self):
        """Test replacing ACs in existing ADF that has an AC section."""
        existing_adf = {
            "type": "doc",
            "version": 1,
            "content": [
                {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": "Introduction"}],
                },
                {
                    "type": "heading",
                    "attrs": {"level": 2},
                    "content": [{"type": "text", "text": "Acceptance Criteria"}],
                },
                {
                    "type": "taskList",
                    "attrs": {"localId": "old-id"},
                    "content": [
                        {
                            "type": "taskItem",
                            "attrs": {"localId": "item-1", "state": "TODO"},
                            "content": [{"type": "text", "text": "Old criterion"}],
                        }
                    ],
                },
                {
                    "type": "paragraph",
                    "content": [
                        {
                            "type": "text",
                            "text": "Generated by Jira AC Assistant on Jan 1",
                            "marks": [{"type": "em"}],
                        }
                    ],
                },
            ],
        }

        new_acs = ["New criterion 1", "New criterion 2"]
        result = replace_acs_in_adf(existing_adf, new_acs)

        assert result["type"] == "doc"
        assert result["version"] == 1

        # Should have: intro paragraph + heading + taskList + attribution
        content = result["content"]
        assert len(content) == 4

        # First element should be preserved intro
        assert content[0]["type"] == "paragraph"
        assert content[0]["content"][0]["text"] == "Introduction"

        # Check the new task list has 2 items
        task_list = content[2]
        assert task_list["type"] == "taskList"
        assert len(task_list["content"]) == 2

    def test_replace_when_no_existing_adf(self):
        """Test creating new document when existing_adf is None."""
        result = replace_acs_in_adf(None, ["New criterion"])

        assert result["type"] == "doc"
        assert result["version"] == 1
        assert len(result["content"]) == 3  # heading + taskList + attribution

    def test_replace_appends_when_no_ac_section_exists(self):
        """Test that ACs are appended when no AC section exists."""
        existing_adf = {
            "type": "doc",
            "version": 1,
            "content": [
                {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": "Just a description"}],
                },
            ],
        }

        result = replace_acs_in_adf(existing_adf, ["New criterion"])

        # Should have: original paragraph + heading + taskList + attribution
        assert len(result["content"]) == 4
        assert result["content"][0]["content"][0]["text"] == "Just a description"
        assert result["content"][1]["type"] == "heading"

    def test_replace_with_empty_acs_removes_section(self):
        """Test that empty ACs list removes the AC section."""
        existing_adf = {
            "type": "doc",
            "version": 1,
            "content": [
                {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": "Introduction"}],
                },
                {
                    "type": "heading",
                    "attrs": {"level": 2},
                    "content": [{"type": "text", "text": "Acceptance Criteria"}],
                },
                {
                    "type": "taskList",
                    "attrs": {"localId": "old-id"},
                    "content": [],
                },
            ],
        }

        result = replace_acs_in_adf(existing_adf, [])

        # Should only have intro paragraph (AC section removed, no new section added)
        assert len(result["content"]) == 1
        assert result["content"][0]["content"][0]["text"] == "Introduction"

    def test_replace_with_none_and_empty_acs(self):
        """Test replacing with None existing_adf and empty ACs."""
        result = replace_acs_in_adf(None, [])

        assert result["type"] == "doc"
        assert result["version"] == 1
        assert result["content"] == []

    def test_replace_preserves_content_after_ac_section(self):
        """Test that content after AC section is preserved."""
        existing_adf = {
            "type": "doc",
            "version": 1,
            "content": [
                {
                    "type": "heading",
                    "attrs": {"level": 2},
                    "content": [{"type": "text", "text": "Acceptance Criteria"}],
                },
                {
                    "type": "taskList",
                    "attrs": {"localId": "old-id"},
                    "content": [],
                },
                {
                    "type": "paragraph",
                    "content": [
                        {
                            "type": "text",
                            "text": "Generated by Jira AC Assistant",
                            "marks": [{"type": "em"}],
                        }
                    ],
                },
                {
                    "type": "heading",
                    "attrs": {"level": 2},
                    "content": [{"type": "text", "text": "Technical Notes"}],
                },
                {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": "Keep this"}],
                },
            ],
        }

        result = replace_acs_in_adf(existing_adf, ["New criterion"])

        # Find the Technical Notes section
        tech_notes_idx = None
        for i, node in enumerate(result["content"]):
            if node.get("type") == "heading":
                text_content = ""
                for c in node.get("content", []):
                    text_content += c.get("text", "")
                if "Technical Notes" in text_content:
                    tech_notes_idx = i
                    break

        assert tech_notes_idx is not None
        # Content after should be preserved
        after_tech_notes = result["content"][tech_notes_idx + 1]
        assert after_tech_notes["content"][0]["text"] == "Keep this"

    def test_replace_handles_invalid_existing_adf(self):
        """Test handling of invalid existing_adf types."""
        result = replace_acs_in_adf("not a dict", ["Criterion"])

        assert result["type"] == "doc"
        assert len(result["content"]) == 3

    def test_replace_handles_missing_content_key(self):
        """Test handling of ADF without content key."""
        existing_adf = {"type": "doc", "version": 1}

        result = replace_acs_in_adf(existing_adf, ["Criterion"])

        assert result["type"] == "doc"
        assert len(result["content"]) == 3

    def test_replace_generates_new_local_ids(self):
        """Test that new task items have unique local IDs."""
        result = replace_acs_in_adf(None, ["Criterion 1", "Criterion 2"])

        task_list = result["content"][1]
        local_ids = [item["attrs"]["localId"] for item in task_list["content"]]
        assert len(set(local_ids)) == 2  # All unique

    def test_replace_sets_todo_state(self):
        """Test that new task items have TODO state."""
        result = replace_acs_in_adf(None, ["Criterion"])

        task_list = result["content"][1]
        task_item = task_list["content"][0]
        assert task_item["attrs"]["state"] == "TODO"

    def test_replace_with_invalid_acs_items(self):
        """Test that invalid AC items are filtered out."""
        result = replace_acs_in_adf(None, ["Valid", "", None, "  ", "Also valid"])

        task_list = result["content"][1]
        assert len(task_list["content"]) == 2

    def test_replace_preserves_pre_ac_content(self):
        """Test that content before AC section is preserved."""
        existing_adf = {
            "type": "doc",
            "version": 1,
            "content": [
                {
                    "type": "heading",
                    "attrs": {"level": 1},
                    "content": [{"type": "text", "text": "Story Title"}],
                },
                {
                    "type": "paragraph",
                    "content": [{"type": "text", "text": "Story description"}],
                },
                {
                    "type": "heading",
                    "attrs": {"level": 2},
                    "content": [{"type": "text", "text": "Acceptance Criteria"}],
                },
                {
                    "type": "taskList",
                    "attrs": {"localId": "old-id"},
                    "content": [],
                },
            ],
        }

        result = replace_acs_in_adf(existing_adf, ["New criterion"])

        # First two elements should be preserved
        assert result["content"][0]["content"][0]["text"] == "Story Title"
        assert result["content"][1]["content"][0]["text"] == "Story description"


class TestEdgeCases:
    """Test suite for edge cases and special scenarios."""

    def test_extract_with_special_characters(self):
        """Test extraction handles special characters in criteria."""
        description = """## Acceptance Criteria

- [ ] User sees "Welcome!" message with <strong>emphasis</strong>
- [ ] API returns {status: "ok"} response
"""
        result = extract_acs_from_description(description)

        assert len(result) == 2
        assert '"Welcome!"' in result[0]
        assert '{status: "ok"}' in result[1]

    def test_extract_with_urls(self):
        """Test extraction handles URLs in criteria."""
        description = """## Acceptance Criteria

- [ ] User is redirected to https://example.com/dashboard
"""
        result = extract_acs_from_description(description)

        assert len(result) == 1
        assert "https://example.com/dashboard" in result[0]

    def test_replace_multiple_times_idempotent(self):
        """Test that replacing multiple times produces consistent results."""
        acs = ["Criterion A", "Criterion B"]

        result1 = replace_acs_in_adf(None, acs)
        result2 = replace_acs_in_adf(result1, acs)

        # Structure should be the same (though IDs will differ)
        assert len(result1["content"]) == len(result2["content"])
        assert result1["content"][0]["type"] == result2["content"][0]["type"]

    def test_extract_non_string_input(self):
        """Test extraction with non-string input."""
        result = extract_acs_from_description(12345)

        assert result == []

    def test_replace_empty_content_list(self):
        """Test replacing in ADF with empty content list."""
        existing_adf = {"type": "doc", "version": 1, "content": []}

        result = replace_acs_in_adf(existing_adf, ["Criterion"])

        assert len(result["content"]) == 3

    def test_extract_handles_different_bullet_styles(self):
        """Test that only checkbox bullets are extracted."""
        description = """## Acceptance Criteria

- [ ] Checkbox item (should extract)
* Regular bullet (should not extract)
- Regular dash bullet (should not extract)
- [x] Another checkbox (should extract)
"""
        result = extract_acs_from_description(description)

        assert len(result) == 2
        assert result[0] == "Checkbox item (should extract)"
        assert result[1] == "Another checkbox (should extract)"
